use mini_usecase;

CREATE TABLE categories (
    category_id INT PRIMARY KEY,
    category_name VARCHAR(50)
);

CREATE TABLE products (
    product_id INT PRIMARY KEY,
    product_name VARCHAR(100),
    category_id INT,
    stock_count INT,
    expiry_date DATE,
    price DECIMAL(10,2),
    FOREIGN KEY (category_id) REFERENCES categories(category_id)
);

CREATE TABLE sales_transactions (
    transaction_id INT PRIMARY KEY,
    product_id INT,
    quantity INT,
    sale_date DATE,
    FOREIGN KEY (product_id) REFERENCES products(product_id)
);

INSERT INTO categories VALUES
(1, 'Type-1'),
(2, 'Type-2'),
(3, 'Type-3');

INSERT INTO products VALUES
(101, 'Milk', 1, 70, CURDATE() + INTERVAL 7 DAY, 30.00),
(102, 'Curd', 1, 30, CURDATE() + INTERVAL 14 DAY, 35.00),
(103, 'Chips', 2, 90, CURDATE() + INTERVAL 30 DAY, 10.00),
(104, 'Orange Juice', 3, 60, CURDATE() + INTERVAL 3 DAY, 50.00),
(105, 'Cool Drinks', 3, 25, CURDATE() + INTERVAL 30 DAY, 20.00);

INSERT INTO sales_transactions VALUES
(1, 101, 10, CURDATE() - INTERVAL 7 DAY),
(2, 103, 15, CURDATE() - INTERVAL 50 DAY),
(3, 101, 5, CURDATE() - INTERVAL 20 DAY),
(4, 104, 20, CURDATE() - INTERVAL 5 DAY);
-- Products expiring soon
SELECT 
    product_name,
    stock_count,
    expiry_date
FROM products
WHERE expiry_date <= CURDATE() + INTERVAL 7 DAY
  AND stock_count > 50;
-- Products not sold from last 60 days
SELECT 
    p.product_id,
    p.product_name
FROM products p
LEFT JOIN sales_transactions s
    ON p.product_id = s.product_id
    AND s.sale_date >= CURDATE() - INTERVAL 60 DAY
WHERE s.product_id IS NULL;
-- Revenue generated by each category
SELECT 
    c.category_name,
    SUM(p.price * s.quantity) AS total_revenue
FROM sales_transactions s
JOIN products p ON s.product_id = p.product_id
JOIN categories c ON p.category_id = c.category_id
WHERE s.sale_date >= CURDATE() - INTERVAL 1 MONTH
GROUP BY c.category_name
ORDER BY total_revenue DESC;
-- Top selling products
SELECT 
    p.product_name,
    SUM(s.quantity) AS total_units_sold
FROM sales_transactions s
JOIN products p ON s.product_id = p.product_id
GROUP BY p.product_name
ORDER BY total_units_sold DESC;
